from django.urls import path
from . import views
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.home, name = "home"),
    path("register", views.register, name = "register"),
    path("login", views.login, name = "login"),
    path("logout", views.logout, name = "logout"),
    path("verify-email/<slug:username>", views.verify_email, name="verify_email"),
    path("resend-otp", views.resend_otp, name="resend_otp"),
    path("auth-url", AuthenticationURL.as_view(), name="auth-url"),
    path("redirect/", views.spotify_redirect, name="redirect"),
    path("check-auth", CheckAuthentication.as_view(), name="check-auth"),
    path("success", views.success, name="success"),
    path("top-artists", views.top_artists, name="top_artists"),
    path("edit-bio", views.edit_bio, name="edit_bio"),
    path("discussion/", views.discussion, name="discussion"),
    path('discussion/comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('discussion/react/<int:post_id>/', views.react, name='react'),
    path("top-tracks", views.top_tracks, name="top_tracks"),
    path("send-friend-request/<str:username>", views.send_friend_request, name="send_friend_request"),
    path("accept-friend-request/<str:username>", views.accept_friend_request, name="accept_friend_request"),
    path("reject-friend-request/<str:username>", views.reject_friend_request, name="reject_friend_request"),
    path("remove-friend/<str:username>", views.remove_friend, name="remove_friend"),
    path("cancel-friend-request/<str:username>", views.cancel_friend_request, name="cancel_friend_request"),
    path("get-current-track", views.get_current_track_endpoint, name="get_current_track"),
    path("api/connections", views.get_connections, name="get_connections"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("api/all_users", views.get_all_users, name="all_users"),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('api/pending_requests', views.pending_requests, name='pending_requests'),
    # Leaderboard endpoints
    path('leaderboard/autocomplete', views.leaderboard_autocomplete, name='leaderboard_autocomplete'),
    path('leaderboard/results', views.leaderboard_results, name='leaderboard_results'),
    path('leaderboard', views.leaderboard_page, name='leaderboard_page'),
    path('friends/', views.friends, name='friends'),
    path('chat/<str:username>/', views.chat, name='chat'),
    path('chat/<str:username>/send', views.send_message, name='send_message'),
    path('chat/<str:username>/messages', views.get_messages, name='get_messages'),
    path('messages/', views.messages_index, name='messages'),
    path('chat/<str:username>/', views.chat, name='chat'),
    path('chat/<str:username>/send/', views.send_message, name='send_message'),
    path('chat/<str:username>/poll/', views.get_messages, name='get_messages'),
    # Swipe / discovery routes
    path('swipe/', views.swipe, name='swipe'),
    path('api/swipe/next', views.api_swipe_next, name='api_swipe_next'),
    path('api/swipe/action', views.api_swipe_action, name='api_swipe_action'),
    path('upload-profile-image/', views.upload_profile_image, name='upload_profile_image'),
    path('set-display-song/', views.set_display_song, name='set_display_song'),
    path('search-track', views.search_track, name='search_track'),
]