# Generated by Django 5.2.7 on 2025-10-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matchifyapp', '0003_add_post_image'),
        ('Matchifyapp', '0003_seen'),
    ]

    operations = [
    ]
