# Generated by Django 4.2.19 on 2025-10-05 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Matchifyapp', '0008_merge_0005_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistListen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('artist_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('total_ms', models.BigIntegerField(default=0)),
                ('play_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_listens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'artist_id')},
            },
        ),
        # Ensure the legacy avatar column exists on the profile table. Some DBs
        # may not yet have the profile table; guard the ALTER with a check for
        # the table's existence so migration can run in any order.
        migrations.RunSQL(
            sql=(
                "DO $$ BEGIN "
                "IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'matchifyapp_profile') THEN "
                "ALTER TABLE matchifyapp_profile ADD COLUMN IF NOT EXISTS avatar varchar(255); "
                "END IF; END$$;"
            ),
            reverse_sql=(
                "DO $$ BEGIN "
                "IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'matchifyapp_profile') THEN "
                "ALTER TABLE matchifyapp_profile DROP COLUMN IF EXISTS avatar; "
                "END IF; END$$;"
            )
        ),
        migrations.DeleteModel(
            name='ProfileAvatar',
        ),
    ]
