# Generated by Django 5.2.7 on 2025-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matchifyapp', '0008_merge_0005_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_song',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, db_column='avatar', null=True, upload_to='profile_images/'),
        ),
        # ProfileAvatar was removed by another migration (0009_artistlisten...).
        # This DeleteModel was duplicated across two independent 0009 files
        # and caused a KeyError during migration graph construction. Removing
        # the duplicate entry here keeps the model deletion only once.
    ]
