# Generated by Django 5.2.7 on 2025-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matchifyapp', '0008_merge_0005_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_song',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, db_column='avatar', null=True, upload_to='profile_images/'),
        ),
        migrations.DeleteModel(
            name='ProfileAvatar',
        ),
    ]
